id: P543D5346
initial_creation_type: input
source_metadata:
  title: Paippalāda-Saṃhitā
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Saṃhitā
  data entry: Arlo Griffiths
  contribution to GRETIL: Arlo Griffiths
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:47:39.268148'
last_modified_at: '2022-03-09T14:47:39.268225'
